WorldBooks/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from catalog import views

urlpatterns = [
    path('', views.index, name='front'),

    re_path(r'^books/?$', views.BookListView.as_view(), name='books'),
    re_path(r'^books/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
    re_path(r'^mybooks/?$', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    re_path(r'^book-create/?$', views.BookCreate.as_view(), name='book-create'),
    re_path(r'^book-update/(?P<pk>\d+)/?$', views.BookUpdate.as_view(), name='book-update'),
    re_path(r'^book-delete/(?P<pk>\d+)/?$', views.BookDelete.as_view(), name='book-delete'),

    re_path(r'^authors/?$', views.AuthorListView.as_view(), name='authors'),
    re_path(r'^authors-add/?$', views.authors_add, name='author-add'),
    path('author-edit/<int:id>/', views.author_edit, name='author-edit'),
    path('author-create/', views.author_create, name='author-create'),
    path('author-delete/<int:id>', views.author_delete, name='author-delete'),

    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls'))
]

catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date


class Genre(models.Model):
    name = models.CharField(max_length=200, help_text='Введите жанр книги', verbose_name='Жанр книги')

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=20, help_text='Введите язык книги', verbose_name='Язык книги')

    def __str__(self):
        return self.name


class Author(models.Model):
    first_name = models.CharField(max_length=100, help_text='Введите имя автора', verbose_name='Имя автора')
    last_name = models.CharField(max_length=100, help_text='Введитк фамилию автора', verbose_name='Фамилия автора')
    date_of_birth = models.DateField(help_text='Введите дату рождения', verbose_name='Дата рождения', null=True, blank=True)
    date_of_death = models.DateField(help_text='Введите дату смерти', verbose_name='Дата смерти', null=True, blank=True)

    def __str__(self):
        full_name = self.first_name + ' ' + self.last_name
        return full_name


class Book(models.Model):
    title = models.CharField(max_length=200, help_text='Введите название книги', verbose_name='Название книги')
    isbn = models.CharField(max_length=13, help_text='Должно содержать 13 символов', verbose_name='ISBN книги')
    summary = models.TextField(max_length=1000, help_text='Введите краткое описание книги', verbose_name='Аннотация кнги')
    genre = models.ForeignKey('Genre', on_delete=models.CASCADE, help_text='Введите жанр книги', verbose_name='Жанр книги', null=True)
    language = models.ForeignKey('Language', on_delete=models.CASCADE, help_text='Введите язык книги', verbose_name='Язык книги', null=True)
    author = models.ManyToManyField('Author', help_text='Введите автора книги', verbose_name='Автор книги')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        # Возвращает URL-адрес для доступа к определённому экземпляру книги
        return reverse('book-detail', args=[str(self.id)])

    def display_author(self):
        return ', '.join([author.last_name for author in self.author.all()])

    display_author.short_description = 'Авторы'


class Status(models.Model):
    name = models.CharField(max_length=20, help_text='Введите статус экземпляра книги', verbose_name='Статус экземпляра книги')

    def __str__(self):
        return self.name


class BookInstance(models.Model):
    inv_nom = models.CharField(max_length=20, help_text='Введите инвентарный номер книги', verbose_name='Инвентарный номер книги', null=True)
    imprint = models.CharField(max_length=200, help_text='Введите издательство и год выпуска', verbose_name='издательство и год выпуска')
    due_back = models.DateField(help_text='Введите конец срока статуса', verbose_name='Конец срока статуса', null=True, blank=True)
    book = models.ForeignKey('Book', on_delete=models.CASCADE, null=True)
    status = models.ForeignKey('Status', help_text='Изменить статус экземпляра', verbose_name='Статус экземпляра', on_delete=models.CASCADE, null=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Заказчик', help_text='Выберите заказчика книги')

    def __str__(self):
        return '%s %s %s' % (self.inv_nom, self.book, self.status)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True

        return False

catalog/forms.py
from django import forms
from datetime import date
from django.forms import ModelForm
from .models import Book


class AuthorsForm(forms.Form):
    first_name = forms.CharField(label='Имя автора')
    last_name = forms.CharField(label='Фамилия автора')
    date_of_birth = forms.DateField(label='Дата рождения', initial=format(date.today()), widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    date_of_death = forms.DateField(label='Дата смерти', initial=format(date.today()), widget=forms.widgets.DateInput(attrs={'type': 'date'}))


class BookModelForm(ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'genre', 'language', 'author', 'summary', 'isbn']
        labels = {'summary': 'Аннотация'}
        help_texts = {'summary': 'Не более 1000 символов'}

catalog/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponseNotFound
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import *
from .forms import *


def index(request):
    # Количество посещений
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    # Получение количества записей
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_authors = Author.objects.all().count()

    # Количество доступных книг
    num_instances_available = BookInstance.objects.filter(status__exact=2).count()

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_visits': num_visits
    }

    return render(request, 'catalog/front.html', context=context)


def authors_add(request):
    authors = Author.objects.all()
    authors_form = AuthorsForm()
    return render(request, 'catalog/author_add.html', {'form': authors_form, 'authors': authors})


def author_create(request):
    if request.method == 'POST':
        author = Author()
        author.first_name = request.POST.get('first_name')
        author.last_name = request.POST.get('last_name')
        author.date_of_birth = request.POST.get('date_of_birth')
        author.date_of_death = request.POST.get('date_of_death')
        author.save()
        return HttpResponseRedirect('/authors-add/')


def author_edit(request, id):
    author = Author.objects.get(id=id)
    if request.method == 'POST':
        author.first_name = request.POST.get('first_name')
        author.last_name = request.POST.get('last_name')
        author.date_of_birth = request.POST.get('date_of_birth')
        author.date_of_death = request.POST.get('date_of_death')
        author.save()
        return HttpResponseRedirect('/authors-add/')
    else:
        return render(request, 'catalog/author_edit.html', {'author': author})


def author_delete(request, id):
    try:
        author = Author.objects.get(id=id)
        author.delete()
        return HttpResponseRedirect('/authors-add/')
    except Author.DoesNotExist:
        return HttpResponseNotFound('<h2>Автор не найден</h2>')


class BookListView(generic.ListView):
    model = Book
    paginate_by = 4


class BookDetailView(generic.DetailView):
    model = Book


class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 2


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    '''
    Универсальный класс представления списка книг, находящихся в заказе у текущего пользователя
    '''

    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='2').order_by('due_back')


class BookCreate(CreateView):
    model = Book
    fields = '__all__'
    success_url = reverse_lazy('books')


class BookUpdate(UpdateView):
    model = Book
    fields = '__all__'
    success_url = reverse_lazy('books')


class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('books')

templates/catalog/author_add.html
{% extends 'catalog/base.html' %}

{% block content %}
    <h3>Список авторов</h3>
    <table>
        <thead>
        <tr>
            <th>Id</th>
            <th>Имя</th>
            <th>Фамилия</th>
            <th>Действие</th>
        </tr>
        </thead>
        <tbody>
        {% if authors %}
            {% for author in authors.all %}
                <tr>
                    <td>{{ author.id }}</td>
                    <td>{{ author.first_name }}</td>
                    <td>{{ author.last_name }}</td>
                    <td>
                        <a href="/author-edit/{{ author.id }}">Изменить</a>
                        <a href="/author-delete/{{ author.id }}">Удалить</a>
                    </td>
                </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="4">Авторов нет</td>
            </tr>
        {% endif %}
        </tbody>
    </table>

    <hr>

    <h3>Добавить автора</h3>
    <form action="/author-create/" method="post">
        {% csrf_token %}
        <table>
            {{ form }}
        </table>
        <input type="submit" value="Сохранить">
    </form>
{% endblock %}

templates/catalog/author_edit.html
{% extends 'catalog/base.html' %}

{% block content %}
    <h3>Список авторов</h3>
    <h4>{{ author.first_name }} {{ author.last_name }}</h4>
    <form action="" method="post">
        {% csrf_token %}
        <p><label for="first_name"></label><input name="first_name" id="first_name" type="text" value="{{ author.first_name }}"></p>
        <p><label for="last_name"></label><input name="last_name" id="last_name" type="text" value="{{ author.last_name }}"></p>
        <p><label for="date_of_birth"></label><input name="date_of_birth" id="date_of_birth" type="date" value="{{ author.date_of_birth.isoformat }}"></p>
        <p><label for="date_of_death"></label><input name="date_of_death" id="date_of_death" type="date" value="{{ author.date_of_death.isoformat }}"></p>
        <input type="submit" value="Отправить">
    </form>
{% endblock %}

templates/catalog/author_list.html
{% extends 'catalog/base.html' %}


{% block content %}
    <h1>Список авторов</h1>
    {% if author_list %}
        {% for author in author_list %}
            <p>
                {{ author.first_name }} {{ author.last_name }},
                <strong>Родился:</strong> {{ author.date_of_birth }},
                <strong>Умер:</strong> {{ author.date_of_death }}
            </p>
        {% endfor %}
    {% else %}
        <p>Авторов не найдено</p>
    {% endif %}
{% endblock %}

templates/catalog/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Мир книг{% endblock %}</title>

    {% load static %}

    <link rel="shortcut icon" href="{% static 'img/logo-tr.png' %}" type="image/png">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/common.css' %}">

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
    <script src="{% static 'js/common.js' %}"></script>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
            {% block sidebar %}
                <ul class="sidebar-nav">
                    <li><a href="{% url 'front' %}">Главная</a></li>
                    <li><a href="{% url 'books' %}">Все книги</a></li>
                    <li><a href="{% url 'book-create' %}">Добавить книгу</a></li>
                    <li><a href="{% url 'authors' %}">Все авторы</a></li>
                    <li><a href="{% url 'author-add' %}">Добавить авторов</a></li>
                    {% if user.is_authenticated %}
                        <li>Пользователь: <strong>{{ user.get_username }}</strong></li>
                        <li><a href="{% url 'my-borrowed' %}">Мои книги</a></li>
                        <li><a href="{% url 'logout' %}?next={{ request.path }}">Выйти</a></li>
                    {% else %}
                        <li><a href="{% url 'login' %}?next={{ request.path }}">Войти</a></li>
                    {% endif %}
                </ul>
            {% endblock %}
        </div>
        <div class="col-sm-10">
            {% block content %}{% endblock %}

            {% block pagination %}
                {% if is_paginated %}
                    <div class="pagination">
                        <span class="page-links">
                            {% if page_obj.has_previous %}
                                <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Предыдущая</a>
                            {% endif %}
                            <span class="page-current">
                                Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
                            </span>
                            {% if page_obj.has_next %}
                                <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">Следующая</a>
                            {% endif %}
                        </span>
                    </div>
                {% endif %}
            {% endblock %}

            {% block footer %}
                {% block copyright %}
                    <div>"Мир книг", 2022.</div>
                {% endblock %}
            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

templates/catalog/book_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <h1>Удаление книги "{{ book.title }}"</h1>
    <p>Вы уверены, что хотите удалить книгу?</p>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Да, удалить книгу">
    </form>
{% endblock %}

templates/catalog/book_detail.html
{% extends 'catalog/base.html' %}

{% block content %}
    <h1>Книга: {{ book.title }}</h1>

    <p><strong>Жанр:</strong> {{ book.genre }}</p>
    <p><strong>Аннотация:</strong> {{ book.summary }}</p>
    <p><strong>ISBN:</strong> {{ book.isbn }}</p>
    <p><strong>Язык:</strong> {{ book.language }}</p>
    {% for author in book.author.all %}
        <p><strong>Автор:</strong> <a href="">{{ author.first_name }} {{ author.last_name }}</a></p>
    {% endfor %}

    <div style="margin-left: 20px; margin-top: 20px;">
        <h4>Количество экземляров книги:</h4>
        {% for copy in book.bookinstance_set.all %}
            <hr>
            <p class="{% if copy.status == 1 %}text-success{% elif copy.status == 2 %}text-danger{% else %}text-warning{% endif %}"></p>
            <p><strong>Издательство:</strong> {{ copy.imprint }}</p>
            <p class="text-muted"><strong>Инвентарный номер:</strong> {{ copy.id }}</p>
            <p><strong>Статус экземпляра книги:</strong> {{ copy.status }}</p>
        {% endfor %}
    </div>
{% endblock %}

templates/catalog/book_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Отправить">
    </form>
{% endblock %}

templates/catalog/book_list.html
{% extends 'catalog/base.html' %}


{% block content %}
    <h1>Список книг</h1>
    {% if book_list %}
        <ul>
            {% for book in book_list %}
                <li>
                    <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{ book.genre }})
                    <span> | </span>
                    <a href="book-update/{{ book.id }}">Изменить</a>
                    <span> | </span>
                    <a href="book-delete/{{ book.id }}">Удалить</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Книг не найдено</p>
    {% endif %}
{% endblock %}

templates/catalog/bookinstance_list_borrowed_user.html
{% extends 'catalog/base.html' %}

{% block content %}
    <h1>Взятые книги</h1>
    {% if bookinstance_list %}
        <ul>
            {% for bookinstance in bookinstance_list %}
                <li class="{% if bookinstance.is_overdue %}text-danger{% endif %}">
                    <a href="{% url 'book-detail' bookinstance.book.pk %}">{{ bookinstance.book.title }}</a> ({{ bookinstance.due_back }})
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Нет выданных книг</p>
    {% endif %}
{% endblock %}

templates/catalog/front.html
{% extends 'catalog/base.html' %}

{% block content %}
    <h1>Мир книг</h1>
    <p>Добро пожаловать в <em>Мир книг</em>. Это простой сайт, созданный на фреймворке Django, который написан на Python.</p>

    <h2>Динамический контент</h2>
    <p>База данных содержит следующее количество записей:</p>
    <ul>
        <li><strong>Количество книг:</strong> {{ num_books }}</li>
        <li><strong>Количество экземпляров книг:</strong> {{ num_instances }}</li>
        <li><strong>Количество доступных для заказа книг:</strong>{{ num_instances_available }}</li>
        <li><strong>Количество авторов книг:</strong> {{ num_authors }}</li>
    </ul>

    <p>Количество посещений данной страницы: {{ num_visits }}</p>
{% endblock %}